### ISSUE TITLE
Не находятся устройства при повторном сканировании

### ISSUE THREAD

**Issue by SamoylichenkoEvgeny** [NeuroMD/neuro-sdk#10]
Си, Windows
Найденные устройства при последующих сканированиях не обнаруживаются. При сканировании не подключаюсь к устройству. Устройства освобождаю между сканированиями.
Если каждый раз пересоздавать сканер, то поиск работает корректно.

**Comment by malochka** [comment]
Windows 10, Unity3d, c#
Воспроизводится полностью.
Если при сканировании не находит устройства то deviceScanner.StopScan() и последующий deviceScanner.StartScan() отрабатывает корректно. До тех пор пока не найдет устройство (тестировал на brainbit). После нахождения устройства, последующее сканирование не работает, и приложение виснет при выходе из программы.
