### ISSUE TITLE
Падение приложения при соединении с устройством

### ISSUE THREAD

**Issue by nazirka** [NeuroMD/neuro-sdk#14]

**Comment by nazirka** [comment]
Добрый день!
Создал консольное приложение, скопировал код из примера SDK 1.3 (.\samples\cpp\device-info), собрал. Выдает сообщение "Connecting device [адрес hex]" и вылетает.
Win10 x64, MS VS 2015.
Отладчик говорит ошибка прав доступа к памяти 0х0000000000000000.
Падает после вызова device_ptr->connect(); функции connectDevice(...).

**Comment by DannyVlasenko** [comment]
Под отладчиком видно, какой именно указатель нулевой? Сам device_ptr? Sdk из инсталлятора используете?

**Comment by nazirka** [comment]
SDK из инсталлятора.
Сам device_ptr не нулевой, после выполнения device_ptr->connect() проходит немного времени и вылетает, видимо в библиотеке создается поток и в нем что-то.

**Comment by nazirka** [comment]
Со старой версией (1.2) девайс работает, до момента прием данных...)
