### ISSUE TITLE
Failed send start receive command

### ISSUE THREAD

**Issue by nazirka** [NeuroMD/neuro-sdk#3]
Добрый день!
В процессе использования SDK v1.2 возник вопрос: после вызова функции "device->execute(Neuro::Command::StartSignal);" в консоле выдается сообщение об ошибке:
"[Neuro::BrainbitImpl::execStartSignalCommand] Failed send start receive command. Error code: 0" или код 255, когда как.
Использую Win8.1 x64. MS VS 2015. 
В чем может быть причина? Похожая ошибка проявляется при запуске приложения из числа примеров sdk (cpp/resistance)

**Comment by DannyVlasenko** [comment]
Привет! Сейчас попробуем разобраться
Как давно девайс получили? Нет с ним информации о его версии?

**Comment by nazirka** [comment]
Девайс получен в субботу (08.09), пока подготовил ОС, установил VS, разбирался с с SDK и только вчера дошел до этого мемента... Версию в документах или программно можно?

**Comment by nazirka** [comment]
И кстати, в примерах для cpp код для channel-data и device-info одинаков

**Comment by DannyVlasenko** [comment]
> Версию в документах или программно можно?
На аккумуляторе или на аккумуляторном блоке должен быть нанесен номер

> И кстати, в примерах для cpp код для channel-data и device-info одинаков
Да, это сейчас действительно так, код примеров будет обновляться с новыми версиями SDK.

Увы, но скорее всего, это совсем новая версия прибора, которую отправили слишком рано. Поддержка этой версии будет в SDK начиная с версии 1.3, которая планируется в эту пятницу

**Comment by nazirka** [comment]
Девас передан мне в работу в субботу, а фирме передан мес. 3-3,5 назад. На андройдовской аппликухе все работает хорошо.

**Comment by DannyVlasenko** [comment]
Понял, спасибо за информацию, сейчас разберемся

**Comment by DannyVlasenko** [comment]
При работе с BLE устройствами на Windows зачастую возникают проблемы со связью, они не всегда одинаково проявляются и их появление зависит от используемого BT-адаптера. Очень часто устранить проблему удается только использованием конкретной модели. Есть возможность попробовать поработать с другим адаптером или на другом ПК?

**Comment by nazirka** [comment]
На ПК с USB адаптером BT вообще не заработало... Будем искать другие ноуты с 8.1 х64

**Comment by DannyVlasenko** [comment]
Не находились устройства или приложение вообще упало?

**Comment by nazirka** [comment]
Не находилось... Хотя другие устройства (телефон, телевизор) соединялись с ним нормально

**Comment by DannyVlasenko** [comment]
Есть возможность попробовать спарить только наш девайс с ПК, а остальные BT-устройства временно с пэйринга снять и попробовать просканировать опять?

**Comment by nazirka** [comment]
попробуем...

**Comment by nazirka** [comment]
Попробовал вариант с встроенным BT-адаптером ноута (который до этого соединялся с устройством, но выдавал ошибку) без наличия остальных устройств - результат тот же - та же ошибка. Попробовал с USB BT-адаптером без наличия остальных устройств - результат тот же - не видит устройства.
Ноут HP Pavilion dv7.

**Comment by nazirka** [comment]
> На аккумуляторе или на аккумуляторном блоке должен быть нанесен номер

в отсеке где установлен аккумулятор написано "bbBase B"

**Comment by nazirka** [comment]
Могу направить на почту свои исходники или собранный exe, чтобы протестировать на Ваших устройствах...

**Comment by DannyVlasenko** [comment]
Приношу свои извинения за такое долгое ожидание! Да, давайте попробуем с исходниками. Cсылку на гитхаб можете кинуть сюда, или архивом на почту vlasenko@neurotech.ru

**Comment by nazirka** [comment]
На прошлой неделе мы отправили наш девайс вам, а взамен получим другой девайс с новой прошивкой. Проверю программу как придет, если не заработает, то вышлю архив на почту.

**Comment by nazirka** [comment]
Получен новый девайс, всё без изменений...
на почту выслал исходный код...

**Comment by nazirka** [comment]
Как успехи, коллеги?

**Comment by DannyVlasenko** [comment]
Добрый день! Письмо с кодом не получил

**Comment by DannyVlasenko** [comment]
Попало в спам, прошу прощения

**Comment by nazirka** [comment]
Бывает)

**Comment by rusregion73** [comment]
Господа, добрый день! Подскажите, пожалуйста, как продвигается вопрос с кодом? Мне тут сообщили, что проблема случилась из-за выхода обновлений Виндовс... вопрос решаемый?

**Comment by rusregion73** [comment]
Господа, добрый день! Есть ли изменения в ситуации? В переписке в прошлый раз руководство называло ориентир по выполнению этой задачи - конец октября... получилось?

**Comment by DannyVlasenko** [comment]
https://github.com/NeuroMD/neuro-sdk/releases/tag/1.3
