### ISSUE TITLE
Ошибка переполнения буфера при работе с датчиком из Unity

### ISSUE THREAD

**Issue by RooKhan** [NeuroMD/neuro-sdk#5]
Описание и скриншот ошибки:[https://docs.google.com/document/d/1e13g1lkTqjDjwpGY1YyyybQ_c5jzNwgU4iNvlsoAMHQ/edit?usp=sharing](url)
Пример кода: https://drive.google.com/open?id=1VrkIs80zPY994o3C4bUzuJObffdFw1uF

По факту датчик отрабатыват 150с получения данных и валится с переполнением буфера.
Как это можно оперативно исправить?

**Comment by DannyVlasenko** [comment]
Добрый день! Скриншот не открывается, к сожалению.
Пример кода в точности такой же как в примере из SDK, в нем нет вызова readData. Есть возможность показать как Вы получаете данные?

**Comment by RooKhan** [comment]
[БагРепорт 22.10.2018.pdf](https://github.com/NeuroMD/neuro-sdk/files/2501171/22.10.2018.pdf)

**Comment by RooKhan** [comment]
получаем данные
с проверкой что не выходим за диапазон
 double[] data = currSignalChannel.ReadData(offset, dataLength);
 offset += data.Length;
ошибка в заполнении буфера

**Comment by RooKhan** [comment]
[BR_22.10.2018.pdf](https://github.com/NeuroMD/neuro-sdk/files/2501187/BR_22.10.2018.pdf)
получаем данные
с проверкой что не выходим за диапазон
 double[] data = currSignalChannel.ReadData(offset, dataLength);
 offset += data.Length;
ошибка в заполнении буфера

**Comment by DannyVlasenko** [comment]
**dataLength** в вызове - это опечатка (data.Length) или это другая переменная?

**Comment by malochka** [comment]
private void Update()
    {
        if (currSignalChannel != null)
        {
            int dataLength = (int)(Time.deltaTime * 1000);

            if (dataLength + offset >= 150000)
            {
                dataLength = offset + dataLength - 150000;
                offset = 0;
            }

            double[] data = currSignalChannel.ReadData(offset, dataLength);
            offset += data.Length;

            totalLenght.text = currSignalChannel.TotalLength.ToString();

            VisualGraph(data);
        }
    }
не совсем корректная запись (будет рассинхнор), но для теста норм

**Comment by DannyVlasenko** [comment]
Спасибо!
Возможно просто произошло недопонимание по поводу интерфейса канала. Буфер лежащий внутри канала действительно циклический, однако это не влияет на способ получения данных, так же как и информация о его длине. Важной с точки зрения пользователя интерфейса здесь является свойство TotalLength. Длина буфера является критической только в том случае, если необходимо вычитать данных больше чем есть. В таком случае отсутствующие данные будут заменены нулями. Но в другой реализации канала, наоборот, может быть что помимо буфера будет еще подкачка с диска, тогда длина буфера будет возвращаться как ноль, а данные заменяться нулями не будут, так как затирающиеся в циклическом буфере данные не будут исчезать бесследно, а будут попадать на диск.

В данном случаем, насколько я понимаю, необходимо вычитать данные, которые поступили за время прошедшее с предыдущего кадра. В таком случае важно убедиться только лишь в том, что данных в канале (не в буфере) больше чем dataLength, что важно на начальном этапе, когда в канале может еще не быть данных. Таким образом получим:
```
if (dataLength >= currSignalChannel.TotalLength) {
    double[] data = currSignalChannel.ReadData(currSignalChannel.TotalLength - dataLength, dataLength);
    totalLenght.text = currSignalChannel.TotalLength.ToString();
    VisualGraph(data);
}
```
Здесь мы получаем ровно те данные, которые были получены за последний кадр. При этом нет необходимости проверять смещение и длину, факт того что буфер циклический скрыт внутри канала, он может быть и не циклическим. Для Вас канал - это непрерывный кусок данных длиной TotalLength. При этом конечно актуальными на данный момент в этом куске будут только последние BufferSize отсчетов. Это ограничение текущей реализации канала, оно будет убрано в ближайших версиях SDK.

**Comment by DannyVlasenko** [comment]
Вылет при неправильных значения offset и length тем не менее не должен происходить, будем исправлять

**Comment by malochka** [comment]
Еще раз проверил, без считывания буфера. 
Оставил только totalLenght.text = currSignalChannel.TotalLength.ToString();
Вылет остается, и именно на 150000. То есть проблема именно в добавлении данных в сам буфер.
В аттаче скриншот, в красном квадрате последнее значение currSignalChannel.TotalLength.
![error](https://user-images.githubusercontent.com/2279827/47312985-6f68e400-d646-11e8-87ef-0050f6c4d682.png)

**Comment by malochka** [comment]
Возможно проблема в том что использую дебаг версию библиотек.
а в circular_buffer.h 
(97) auto newTail = mDataLength > 0 ? mTail + length : mTail + length - 1;
итератор выходит за предел массива. и, как [пишут](https://social.msdn.microsoft.com/Forums/vstudio/en-US/99a01298-865d-4451-b8c6-3e25db5cbcee/vector-iterator-offset-out-of-range?forum=vclanguage), при вызове из с#  c++ могут быть отличия релизной и дебаг версии (возможно в релизе отключены проверки).

**Comment by malochka** [comment]
да, проверил, релизная версия библиотек работает.

**Comment by DannyVlasenko** [comment]
Спасибо за исследование!
Проблема о которой я забыл. Да действительно, в том месте производится арифметическая операция с итератором, в результате которой итератор выходит за допустимые границы. Это естественно неопределенное поведение, корни которого идут от старой реализации буфера, которая была сделана на С. А так как поведение не определено, то в реализации STL в MSVC для debug-билда стоит проверка на границы контейнера, что допустимо с точки зрения стандарта. Ни в gcc, ни в clang такой проверки нет, только в MSVC, поэтому этот баг до сих пор жил, хоть и не наносил вреда кроме данного случая.
Будет исправлено в версии 1.3

**Comment by DannyVlasenko** [comment]
https://github.com/NeuroMD/neuro-sdk/releases/tag/1.3
