### ISSUE TITLE
Падение при попытке вызова SignalChannel(device, channelInfo)

### ISSUE THREAD

**Issue by malochka** [NeuroMD/neuro-sdk#6]
C# Unity3d, net-neurosdk.dll(release), c-neurosdk.dll, neurosdk.dll 

При вызове  new SignalChannel() без channelInfo работает нормально
Пример:
       var signalChannel = new SignalChannel(device);
channelInfo Name="Signal" Type="Signal" Index=0

При вызове SignalChannel() с channelInfo падение приложения (без Exception, хотя код выполняется внутри try...catch)
Пример:
        ChannelInfo channelInfo;
        channelInfo.Index = UIntPtr.Zero;
        channelInfo.Type = ChannelType.Signal;
        channelInfo.Name = "Signal";
        var signalChannel = new SignalChannel(device, channelInfo);

**Comment by DannyVlasenko** [comment]
Привет!
Конструктору SignalChannel необходимо, по возможности, передавать объект ChannelInfo полученный из листа каналов устройства, т.е. из тех, которые содержаться в Device.Channels

**Comment by malochka** [comment]
Добрый день.
При передаче тоже самое
        foreach (var channel in device.Channels)
        {
            if (channel.Type == ChannelType.Signal)
            {
                Console.WriteLine($"Start    -{channel.Name}");
                var signalChannel = new SignalChannel(device, channel);
                signalChannel.LengthChanged += SignalChannel_LengthChanged;
            }
        }

**Comment by DannyVlasenko** [comment]
https://github.com/NeuroMD/neuro-sdk/releases/tag/1.3
