### ISSUE TITLE
Ошибка определения типа

### ISSUE THREAD

**Issue by malochka** [NeuroMD/neuro-sdk#7]
Windows 8.1 Windows Kit 10.0.17763.0
GUID в ble_device_win.cpp(21) не определен.
повторяется как и в VS2017 так и при использовании build-all.cmd
![i561 cimgpsh_orig](https://user-images.githubusercontent.com/2279827/49832957-311bb580-fda9-11e8-9cb2-b64325a25cec.png)

E:\projects\Med\Neuro\neuro-sdk-1.3\core\ble\win\ble_device_win.cpp(21): error
C4430: missing type specifier - int assumed. Note: C++ does not support default
-int [E:\projects\Med\Neuro\neuro-sdk-1.3\core\build\x86\neurosdk.vcxproj]
E:\projects\Med\Neuro\neuro-sdk-1.3\core\ble\win\ble_device_win.cpp(21): error
C2146: syntax error: missing ';' before identifier 'guid_from_string' [E:\proje
cts\Med\Neuro\neuro-sdk-1.3\core\build\x86\neurosdk.vcxproj]
E:\projects\Med\Neuro\neuro-sdk-1.3\core\ble\win\ble_device_win.cpp(21): error
C2143: syntax error: missing ';' before '{' [E:\projects\Med\Neuro\neuro-sdk-1.
3\core\build\x86\neurosdk.vcxproj]

**Comment by malochka** [comment]
замена GUID на winrt::guid позволяет скомпилировать проект

**Comment by DannyVlasenko** [comment]
Все верно, вы используете версию Windows Kits, которая поставляется с Windows 10 1809, в которой классическая структура для GUID уже не используется. Однако все необходимые нам WinRT API доступны начиная с версии 1803, поэтому мы используем версию Windows Kits 10.0.17134.0. Так как на новой версии Windows Kits сборки не проверялись, пока нет гарантии, что на ней все будет работать стабильно, не смотря на успешную компиляцию.
Установочные файлы уже собранных библиотек SDK вы можете найти здесь:
http://wiki.callibri.com/index.php?title=Binaries_and_downloads#Windows
Обратите внимание, что не смотря на то, что у вас установлен windows kit 10 на win 8.1, у ваших пользователей с большой вероятностью приложение сможет работать только на win10 версии не ниже 1803.
